name: LCW Stok Takip

on:
  schedule:
    # Her 5 dakikada bir çalıştırır
    - cron: '*/5 * * * *'
  workflow_dispatch:
    # Manuel olarak da çalıştırabilmek için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@v3

    - name: Python Ortamını Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Gerekli Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Stok Kontrol Scriptini Çalıştır
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
